@CheckNSell_HostAddress = http://localhost:5036/api

GET {{CheckNSell_HostAddress}}/Product/testconnectdb
Accept: application/json

###

// Get all products
GET {{CheckNSell_HostAddress}}/Product
Accept: application/json

###

// Get product by id
GET {{CheckNSell_HostAddress}}/Product/3
Accept: application/json

###

// Add new product
POST {{CheckNSell_HostAddress}}/Product
Content-Type: application/json
Accept: application/json

{
  "category_id": 1,
  "product_name": "Mobile Product New",
  "unit_price": 10,
  "product_picture": "https://www.popticles.com/wp-content/uploads/2021/04/iphone-410311_1280-1024x682.jpg",
  "unit_in_stock": 100,
  "created_date": "2021-07-01T00:00:00",
  "modified_date": "2021-07-01T00:00:00"
}

###

// Update product
PUT {{CheckNSell_HostAddress}}/Product/5
Content-Type: application/json
Accept: application/json

{
  "category_id": 1,
  "product_name": "Mobile Product Updated",
  "unit_price": 20,
  "product_picture": "https://www.popticles.com/wp-content/uploads/2021/04/iphone-410311_1280-1024x682.jpg",
  "unit_in_stock": 200,
  "created_date": "2021-07-01T00:00:00",
  "modified_date": "2021-07-01T00:00:00"
}

###

// Delete product
DELETE {{CheckNSell_HostAddress}}/Product/5
Accept: application/json